/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Frames.HomeWindow;
import Networking.MyClient;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BIT2
 */
public class Receiver_Loader extends javax.swing.JInternalFrame {

    javax.swing.JDesktopPane desktopPane;
    HomeWindow window;

    /**
     * Creates new form Receiver_Loader
     */
    public Receiver_Loader(javax.swing.JDesktopPane desktopPane, HomeWindow homeWindow) {
        window = homeWindow;
        this.desktopPane = desktopPane;
        initComponents();
        System.out.println("ffffff");
        server1Logo.setVisible(false);
        server2Logo.setVisible(false);
        server3Logo.setVisible(false);
        server4Logo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        server2Logo = new javax.swing.JLabel();
        server1Logo = new javax.swing.JLabel();
        server3Logo = new javax.swing.JLabel();
        server4Logo = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ripple (1).gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Chiller", 3, 24)); // NOI18N
        jLabel2.setText("Searching for Servers");

        server2Logo.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        server2Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png"))); // NOI18N
        server2Logo.setText("192.168.43.1");
        server2Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        server2Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                server2LogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                server2LogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                server2LogoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                server2LogoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                server2LogoMouseReleased(evt);
            }
        });

        server1Logo.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        server1Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        server1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png"))); // NOI18N
        server1Logo.setText("192.168.43.1");
        server1Logo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        server1Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        server1Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                server1LogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                server1LogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                server1LogoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                server1LogoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                server1LogoMouseReleased(evt);
            }
        });

        server3Logo.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        server3Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png"))); // NOI18N
        server3Logo.setText("192.168.43.1");
        server3Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        server4Logo.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        server4Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png"))); // NOI18N
        server4Logo.setText("192.168.43.1");
        server4Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(server1Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(server2Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(server4Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(server3Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addComponent(server1Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(server2Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(server4Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(server3Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void server2LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server2LogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_server2LogoMouseClicked

    private void server2LogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server2LogoMouseEntered
        server2Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/server_button_hover.png")));
    }//GEN-LAST:event_server2LogoMouseEntered

    private void server2LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server2LogoMouseExited
        server2Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png")));
    }//GEN-LAST:event_server2LogoMouseExited

    private void server2LogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server2LogoMousePressed
        server2Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/server_button_pressed.png")));
    }//GEN-LAST:event_server2LogoMousePressed

    private void server2LogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server2LogoMouseReleased
        server2Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png")));
    }//GEN-LAST:event_server2LogoMouseReleased

    private void server1LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server1LogoMouseClicked
        MyClient client = new MyClient(server1Logo.getText().toString(),window);
        window.myClient=client;
        client.initiate();
        desktopPane.removeAll();
        Chooser_Frame cf = new Chooser_Frame(window,server1Logo.getText().toString());
        desktopPane.add(cf);
        cf.show();
    }//GEN-LAST:event_server1LogoMouseClicked

    private void server1LogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server1LogoMouseEntered
        server1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/server_button_hover.png")));
    }//GEN-LAST:event_server1LogoMouseEntered

    private void server1LogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server1LogoMouseExited
        server1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png")));
    }//GEN-LAST:event_server1LogoMouseExited

    private void server1LogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server1LogoMousePressed
        server1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/server_button_pressed.png")));
    }//GEN-LAST:event_server1LogoMousePressed

    private void server1LogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_server1LogoMouseReleased
        server1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.png")));
    }//GEN-LAST:event_server1LogoMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel server1Logo;
    public javax.swing.JLabel server2Logo;
    public javax.swing.JLabel server3Logo;
    public javax.swing.JLabel server4Logo;
    // End of variables declaration//GEN-END:variables
}
